[build]
target = "riscv32i-unknown-none-elf"

[target.riscv32i-unknown-none-elf]
rustflags = [
    "-C",
    "link-arg=-Tlinker.ld",
    "-Z",
    "unstable-options",
    "-C",
    "target-feature=+m,+a",
]
